### ISSUE TITLE
Improve the HUD and add zooming + scrolling

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#29]
The HUD is currently not looking super awesome due to the separation between the HUD elements on the left and the actual level area in the middle. We should probably look everything on top of the level area and/or design some nice HUD overlay.

If some HUD elements are on top of the level area, we also need to be able to zoom in and out and scroll within this area, maybe a Camera2D can be used for that.

**Comment by bojidar-bg** [comment]
Scrolling done in 620d8fc3f718981ff8b47d19cf8d859c315bbb3a by @akien-mga

**Comment by fry-** [comment]
I would rather go with an overlay for the HUD, instead of making it on top of the visible game board. A changing background is always hard for the eye to easily see the buttons (sometimes it has to go quick, and this disturbs a lot). I'd rather go the way like RTS games do it. Also I would keep the buttons on the side of the screen, because it splits the screen better, but move it to the right side since that is also the usual mouse position on your desk (I think its easier for the brain on an subconscious level). Stuff like the display how much money, life and mana you have can move to a top bar though, since they don't take much space.
Here some examples from C&C to get inspired:
[C&C 1](https://troublmaker.files.wordpress.com/2012/04/commandandconqer1.jpg)
[C&C 3](https://bosstigercnc3.files.wordpress.com/2012/02/command-and-conquer-3-harvester.jpg?w=1024)
[C&C 4](http://techxav.com/wp-content/uploads/2010/03/command_and_conquer_4_7.jpg)

**Comment by ObaniGemini** [comment]
@fry- : I totaly agree with you on that.

**Comment by bojidar-bg** [comment]
@fry- ~ I mostly done it following your suggestions, can you check?

Here are some screens:
![image](https://cloud.githubusercontent.com/assets/5276727/13549684/b9e011bc-e313-11e5-8a39-3a65f4caf69b.png)
![image](https://cloud.githubusercontent.com/assets/5276727/13549687/c73a20a0-e313-11e5-8a44-315f4decad90.png)
![image](https://cloud.githubusercontent.com/assets/5276727/13549691/d6967850-e313-11e5-8a88-9fbeabff6a29.png)

**Comment by bojidar-bg** [comment]
@fry- ~ Now the healthbar and the stats are on the same line :smile:
